### ISSUE TITLE
Download.py

### ISSUE THREAD

**Issue by siyilingting** [lichengunc/vist_api#1]
Hi, licheng.
Thank you for your sharing. I'm curious that are there difference between the VIST dataset downloaded from [http://www.visionandlanguage.net/VIST/dataset.html](url) and downloaded by your _download.py_ ? It has token me a long time to download the it from the VIST website and I would like to use your _vist.py_ to deal with them.

**Comment by lichengunc** [comment]
download.py is able to download all the photo images from google-cloud together. Yes, it takes time as the whole size is 300GB.

**Comment by siyilingting** [comment]
Actually, I have extracted features for images downloaded from VIST website and find that about 40 jpg images can not be read. Is this normal? Is it necessary for me to re-download dataset by your script?

**Comment by lichengunc** [comment]
Yes, there are some broken images. :-)

**Comment by siyilingting** [comment]
Thank you.
